### ISSUE TITLE
Cant Able to Download Album

### ISSUE THREAD

**Issue by L0nelyW0lf** [prabaprakash/Saavn-Downloader#11]
Enter the url:https://www.saavn.com/s/album/hindi/Stree-2018/5hyqYg65lRs_
...
Initiating Album Downloading
...
Please paste link of album or playlist

This is what it says whenever i paste a album url & playlist Download works fine.

**Comment by shammu4real** [comment]
Am also getting the same issue....

**Comment by shammu4real** [comment]
Again same issue started...

Enter the url:https://www.saavn.com/s/album/tamil/Genius-2018/H1shvIZhbg0_
...
Initiating Album Downloading
...
Please paste link of album or playlist

**Comment by sagarag21** [comment]
Not able to download
