### ISSUE TITLE
songid

### ISSUE THREAD

**Issue by MayuraVerma** [prabaprakash/Saavn-Downloader#17]
I am not use able to 
getSong(songId)

I have a song id "qLZhFr8y"

https://www.saavn.com/api.php?songid=qLZhFr8y&_format=json&__call=song.getDetails

the above get is giving error
{"error":{"code":"INPUT_MISSING","msg":"One or more required field missing:pids"}}

I am not if I am extracting the song id or if the syntax is wrong.

Also, I am trying extract lyricist. This information is only available in the song url. Although the album is json dump has the lyricist, it is dumped inside artists along with singers. So, we need to query the song url to extract the lyricist.

**Comment by prabaprakash** [comment]
Sorry @MayuraVerma  I didn't close the issue long back...

**Comment by MayuraVerma** [comment]
Is it resolved now?

**Comment by prabaprakash** [comment]
@MayuraVerma  I just made it simpler version. Just download album and playlist.
