### ISSUE TITLE
lxml lib does not work with latest python on win10

### ISSUE THREAD

**Issue by sgbhavsar** [prabaprakash/Saavn-Downloader#2]
I am new in python and tried to get it work but latest python does not able to install lxml library automatically and manual installation required python 3.4. Python 3.4 pip3 installer ask microsoft c++ 10 runtime, when downloaded and install it says newer version is installed.

**Comment by prabaprakash** [comment]
Could you tried this solution, https://stackoverflow.com/questions/49610212/pip-error-even-microsoft-visual-c-14-0-is-installed
