### ISSUE TITLE
Not able to Download

### ISSUE THREAD

**Issue by sagarag21** [prabaprakash/Saavn-Downloader#22]
It Keeps on saying "please paste link of album or playlist"
Screenshot :: https://drive.google.com/open?id=1VhXjgB9deYOt01ZwJrWH0wMv4_WI-nmB

**Comment by aryanvikash** [comment]
I m Not sure but  you can try these .
Case 1: Check song dir. If there is  file with same name, delete it and try again.  
Case 2 : because you are providing a single song url . Try with album url

**Comment by aryanvikash** [comment]
> It Keeps on saying "please paste link of album or playlist"
> Screenshot :: https://drive.google.com/open?id=1VhXjgB9deYOt01ZwJrWH0wMv4_WI-nmB


I m Not sure but you can try these .
Case 1: Check song dir. If there is file with same name, delete it and try again.
Case 2 : because you are providing a single song url . Try with album url

**Comment by inovachrono** [comment]
> It Keeps on saying "please paste link of album or playlist"
> Screenshot :: https://drive.google.com/open?id=1VhXjgB9deYOt01ZwJrWH0wMv4_WI-nmB

Are you sure about the url you are entering. I pasted the same url that you used in the image above and it returns a 404 page. However if you replace the 0(zero) in "I0j" with O(capital o) as "IOj" then you get the correct page. For instance the actual url in your case is https://www.jiosaavn.com/album/96/buIOjYZDrNA_

**Comment by ar7x9** [comment]
Tried downloading that album, it worked. This should be closed
@monuyadav016 is correct

**Comment by rdkannan** [comment]
I am also getting the same issue mention by @sagarag21. After going thro line of code, it was due to  [https://github.com/prabaprakash/Saavn-Downloader/issues/27](url)
try adding below line under pre-configuration section then it worked fine for me

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

Before : https://ibb.co/TtVvVPB
After :https://ibb.co/rGtkhwV
