### ISSUE TITLE
Download limited upto 49 songs #Hacktoberfest 

### ISSUE THREAD

**Issue by muppathimoonu** [prabaprakash/Saavn-Downloader#23]
This script is not downloading the entire playlist.
It only downloads 49 songs from the playlist and exit,

**Comment by inovachrono** [comment]
I tried it with a playlist of 56 songs and i was able to download 47 successfully. I'll have to test this again with another playlist.

**Comment by muppathimoonu** [comment]
Issue occurs only while using in a linux machine. It downloads whole playlist in my mac, I have no idea how this works in a windows machine,

**Comment by prabaprakash** [comment]
Let me check it

**Comment by prabaprakash** [comment]
@muppathimoonu  It works fine Linux machine. I checked it. reopen it, if you issue again
