### ISSUE TITLE
Feature Request : Add support for Saavn Originals (Podcasts)

### ISSUE THREAD

**Issue by ar7x9** [prabaprakash/Saavn-Downloader#26]
Title

**Comment by inovachrono** [comment]
> Title

Your requested feature has been added to my fork [monuyadav016/Saavn-Downloader](https://github.com/monuyadav016/Saavn-Downloader)

**Comment by avishj** [comment]
> 
> 
> > Title
> 
> Your requested feature has been added to my fork [monuyadav016/Saavn-Downloader](https://github.com/monuyadav016/Saavn-Downloader)

~Doesn't work for me. Tells me to "Please paste link of album or playlist".~



Never Mind, I'm stupid.

**Comment by inovachrono** [comment]
> Never Mind, I'm stupid.

You need to login with your credentials to use this feature. Also make sure they are part of your library.

I requests all issues that are solved to be closed.

**Comment by prabaprakash** [comment]
@monuyadav016 thanks for help out this folks, so kind of you. Focus on your studies too.
