### ISSUE TITLE
SSL Certificate verfiy failure

### ISSUE THREAD

**Issue by rdkannan** [prabaprakash/Saavn-Downloader#27]
Hi,
I am getting below error while running this in my mac and this exception was caused by SmartDL.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

To overcome the issue, I have added the below line and worked for me.

# Pre Configurations
ssl._create_default_https_context = ssl._create_unverified_context 

Hope this can help someone else too. 
Thanks again for creating downloader and very helpful to me

**Comment by prabaprakash** [comment]
Fixed it
