### ISSUE TITLE
character " is downloaded as '&quot;'

### ISSUE THREAD

**Issue by dineshkoravi** [prabaprakash/Saavn-Downloader#28]
If the name metadata contains " character, it is saved as `&quot;`

example album : https://www.jiosaavn.com/album/psycho-saiyaan-from-saaho/D0ZXR2UMNLs_

![image](https://user-images.githubusercontent.com/10230051/61399428-cbb61700-a8eb-11e9-9962-3a75ee05620d.png)

Screenshot from Windows Details Pane:
![image](https://user-images.githubusercontent.com/10230051/61399502-f30ce400-a8eb-11e9-9b3d-99e7cb58d434.png)

**Comment by dineshkoravi** [comment]
here is the PR for this issue : https://github.com/prabaprakash/Saavn-Downloader/pull/35

**Comment by prabaprakash** [comment]
@dineshkoravi Thanks
