### ISSUE TITLE
Stops download of album midway.

### ISSUE THREAD

**Issue by twisp007** [prabaprakash/Saavn-Downloader#3]
After pasting the album link it download a few songs and then stops midway. Prints: `Please paste link of album or playlist`

I modified the following lines from `__main__ `:

```
except Exception as e:
        print('...')
```

as 

```
except Exception as e:
        print('...', e)
```

then it prints: `... error() missing 1 required positional argument: 'msg'`

**Comment by twisp007** [comment]
Ok. I finally had some time and found out what the issue is.

You assume all the songs have high quality m4a versions. That does not seem to be the case or at least the programs fails to retrieve that all the time. Sometimes it's just low quality mp3s.

So when the program encounters a mp3 it still assumes it's an m4a file and tries to "tag" it but of course fails since it can only tag m4a files. Now the program should move onto the next file but this module "logger" is not properly handled and it is also throwing an error obscuring the original error.

**So this program cannot handle mp3 songs and fails because it always assumes the audio format will be m4a.**

What I don't know is does the programs fails to retrieve high quality audio files or is there no high quality audio file to be served for that particular song...

Anyway I am posting some albums for testing:

    s/album/telugu/Varudu-2010/YB8TSYHlmZA_
    s/album/telugu/Aditya-369-1991/LLNV5m9aMtw_
    s/album/telugu/Yuvakudu-2000/rhOmdNRABLw_


Also please let me know if you don't have time for this project.

**Comment by prabaprakash** [comment]
If you have time. please contribute to fixing this.

**Comment by iodize6399** [comment]
Another issue, I found maybe not related to script but how IDLE works on Windows 10, if I resize midway or unfocus the download window, the scripts stops midway
