### ISSUE TITLE
Some songs are only half downloaded

### ISSUE THREAD

**Issue by Maniarasan** [prabaprakash/Saavn-Downloader#30]
Some songs play only till half , please correct identify and correct the issue

**Comment by prabaprakash** [comment]
Looking into it, check-in Linux environment

**Comment by prabaprakash** [comment]
Guys, someone fix it. it bit tight with work

**Comment by dineshkoravi** [comment]
Any specific album URL to test this?

**Comment by Maniarasan** [comment]
@dineshkoravi 
You can try the below specified URL
https://www.jiosaavn.com/s/playlist/arasuseran455/Arasu_collection/fF0uOjid-,E_

**Comment by dineshkoravi** [comment]
Is there any specific song that is half downloaded ?

**Comment by nousernamedeveloper** [comment]
@dineshkoravi 
https://www.jiosaavn.com/album/kohinoor/diEhJGcmcaU_
check this 
the second song wallah is only half downloaded

**Comment by prabaprakash** [comment]
@dineshkoravi I'm closing this issue. It's probably due slow speed. If you still face it re-open it
