### ISSUE TITLE
Set download location

### ISSUE THREAD

**Issue by terminal77** [prabaprakash/Saavn-Downloader#31]
Hey bud,
Can you please setup the download script to accept an argument for download location. Ping me once its done and I will make a docker image for this.
Cheers

**Comment by inovachrono** [comment]
I understand that downloading to the same folder becomes cubersome. I added a condition to ask if the user wants to create a new directory. 


https://github.com/monuyadav016/Saavn-Downloader/commit/a83b5965dfcd18e5d4a43522ce8ed46173bbaede

**Comment by prabaprakash** [comment]
I'm sorry @monuyadav016 , It need to so simple design
