### ISSUE TITLE
Saavn API to get a list of all my music

### ISSUE THREAD

**Issue by terminal77** [prabaprakash/Saavn-Downloader#32]
Does anyone here knows if any Saavn API exists to pull all the albums in my music? Unfortunately it does not even exist in web player so hard to find the links of all albums in my music.

**Comment by prabaprakash** [comment]
I don't know you. Always there is a way to go it.  No system is perfect

**Comment by inovachrono** [comment]
How is this even in the issues section. Though its a good question, it does not belong here.

**Comment by terminal77** [comment]
I know it's not an issue with this repository but posted here thinking someone might have figured this out or OP might have some experience working with Saavn API.

**Comment by inovachrono** [comment]
> Does anyone here knows if any Saavn API exists to pull all the albums in my music? Unfortunately it does not even exist in web player so hard to find the links of all albums in my music.

I have updated my fork [monuyadav016/Saavn-Downloader](https://github.com/monuyadav016/Saavn-Downloader) to solve what you are looking for.

**Comment by terminal77** [comment]
Thanks a lot @monuyadav016 . Really appreciate your work. However I'm hitting an issue when using 'python3 Download.py -a' , it downloads first two albums but then fails wit this error:
```
Album name:  None
Traceback (most recent call last):
  File "Download.py", line 285, in <module>
    downloadAllAlbums(getLibrary())
  File "Download.py", line 215, in downloadAllAlbums
    album_name = album_nm.replace("&quot;", "'")
AttributeError: 'NoneType' object has no attribute 'replace'
```
Can you please look into this. Thanks again!

**Comment by inovachrono** [comment]
> Album name:  None
> Traceback (most recent call last):
>   File "Download.py", line 285, in <module>
>     downloadAllAlbums(getLibrary())
>   File "Download.py", line 215, in downloadAllAlbums
>     album_name = album_nm.replace("&quot;", "'")
> AttributeError: 'NoneType' object has no attribute 'replace'

I can make out that the data was not parsed properly.  Though I have no Idea which album caused this issue. So I have simply added a exception handling for such albums. So next time you can paste the line that says "Error getting album with ID:". So these album should be skipped for now.


Also I want to inform you that only those albums that have a heart mark are part of your library. Not every album that you see in the albums sections may not be part of your library, so they will not be downloaded.

I'll gladly except any further feedback.

**Comment by terminal77** [comment]
Thanks a lot man. That worked perfectly.

> Also I want to inform you that only those albums that have a heart mark are part of your library. Not every album that you see in the albums sections may not be part of your library, so they will not be downloaded.
Yeah found that out, it sucks because of most of my library is just downloaded to phone never clicked on that hear icon to add to my library.

The only thing I can request is if possible, add an option to download all the albums of an artist( we can give the link to artist in Saavn as an argument)

Thanks again for all your work.
P.S: The word 'except' mean something different, I'm guessing you wanted to say 'accept' :) (Not trying to be grammar nazi but just so you know)

**Comment by inovachrono** [comment]
I have added the requested enhancement. Now you can download all albums of an artist. Though each albums will have its own folder, you should be careful to segregate other albums before running the newly added -artist command. Because almost all popular artist have more than 100's of albums. I tested the script with Arijit Singh and he alone has 692 albums. So you probably should move other downloaded albums beforehand otherwise they'll all mix up and that will be the end of well maintained Library. I'll change this in a later update to download artist albums in a folder by artist name.

> P.S: The word 'except' mean something different, I'm guessing you wanted to say 'accept' :) (Not >trying to be grammar nazi but just so you know)

Yeah that's a typo.

**Comment by inovachrono** [comment]
I came here to say that I have updated the script and now you no longer need to worry about the albums cluttering and destroying your library structure.

**Comment by terminal77** [comment]
Man, that's perfect. Thank you so much. Truly appreciated.

**Comment by inovachrono** [comment]
> Man, that's perfect. Thank you so much. Truly appreciated.

You can show appreciation in github way by liking the project so that people can find my project easily.

Downloading from youtube is not the best experience because youtube has only 128kbps even for Youtube Songs.

I like the fact that people want to keep their songs offline just like old days rather than streaming it from a platform online everytime they want to listen to one.

**Comment by terminal77** [comment]
> You can show appreciation in github way by liking the project so that people can find my project easily.

Done

> Downloading from youtube is not the best experience because youtube has only 128kbps even for Youtube Songs.

Yep and it'll be a pain to manage metadata for youtube downloads.

> I like the fact that people want to keep their songs offline just like old days rather than streaming it from a platform online everytime they want to listen to one.

Agreed, I actually pay for Saavn Pro, but the fact that they can take songs offline anytime infuriates me. So many times songs in my playlists have been marked 'Unavailable'. So I really wanted to keep an offline copy of everything, eventually I'll just run my own music server (for personal use only).

**Comment by prabaprakash** [comment]
@monuyadav016  Will you make a pull request to merge those fixes. I just fixed fetching playlist and album it.
