### ISSUE TITLE
Doesnt download playlist anymore

### ISSUE THREAD

**Issue by chanpreetsal** [prabaprakash/Saavn-Downloader#36]
The script stopped download playlist. I can download albums just fine.

here is a sample playlist to try to download - https://www.jiosaavn.com/s/playlist/chanpreet381/DiwaliClass/scI6-Lp1j3zufxkxMEIbIw__

**Comment by monuyadav016** [comment]
The formatting of the page was giving an empty list to songs_json.

https://github.com/monuyadav016/Saavn-Downloader/commit/3e0a68b749a9f39566f7837a57147a3be983b027

**Comment by inovachrono** [comment]
You can download my fork [monuyadav016/Saavn-Downloader](https://github.com/monuyadav016/Saavn-Downloader) until its merged with mine or this issue is fixed by changing the lambda function.

**Comment by chanpreetsal** [comment]
Great. The folked solution works

**Comment by inovachrono** [comment]
> Great. The folked solution works

Maybe you should look at the other added features as well.

**Comment by prabaprakash** [comment]
Awesome @monuyadav016  looking into it. give me just few days, I'm stuck up with work
