### ISSUE TITLE
MP3 Format

### ISSUE THREAD

**Issue by Isuru29** [prabaprakash/Saavn-Downloader#4]
Good if it has option to change m4a to mp3

**Comment by ghost** [comment]
They switched from mp3 to m4a. M4A is also better.

**Comment by Isuru29** [comment]
But some portable players don't support m4a , Is there option to change the format to mp3?

**Comment by shammu4real** [comment]
Can someone help... Am getting this error...

C:\Users\Shammu\AppData\Local\Programs\Python\Python37\Scripts\Saavn-Downloader>Download.py
Enter the url:https://www.saavn.com/s/song/tamil/Kavalai-Vendam/Un-Kadhal-Irundhal-Podhum/BgQICCdYeV8
Traceback (most recent call last):
  File "C:\Users\Shammu\AppData\Local\Programs\Python\Python37\Scripts\Saavn-Downloader\Download.py", line 157, in <module>
    soup = BeautifulSoup(res.text, "lxml")
  File "C:\Users\Shammu\AppData\Local\Programs\Python\Python37\lib\site-packages\beautifulsoup4-4.6.0-py3.7.egg\bs4\__init__.py", line 165, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by Isuru29** [comment]
pip install bs4

**Comment by haze** [comment]
@Isuru29 if you really want mp3 that badly just re-encode the files yourself.

**Comment by akshaybengani** [comment]
Use FFMPEG to convert m4a to mp3.
