### ISSUE TITLE
 Could not find a version that satisfies the requirement request.

### ISSUE THREAD

**Issue by sankalpgaikwad** [prabaprakash/Saavn-Downloader#42]
C:\Users\Desktop\github\saavn>pip install -r requirements.txt
Requirement already satisfied: BeautifulSoup4 in c:\users\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 1)) (4.9.1)
Requirement already satisfied: eyed3 in c:\users\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 2)) (0.9.5)
Requirement already satisfied: urllib3 in c:\users\appdata\local\programs\python\python38\lib\site-packages (from -r requirements.txt (line 3)) (1.25.10)
ERROR: Could not find a version that satisfies the requirement request (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for request (from -r requirements.txt (line 4))

**Comment by sankalpgaikwad** [comment]
can anyone help me with this

**Comment by mpeddu** [comment]
Use this " pip install https://files.pythonhosted.org/packages/03/87/591f84ef3b785f9f3f807033ae4a40f219b8a7e33e5d1a0862d1b2532a84/request-1.3.1-py3-none-any.whl "

**Comment by sankalpgaikwad** [comment]
All packages are installed correctly but now it is not downloading any album or playlist. Its says please paste album/playlist url.

C:\Users\Desktop\github\saavn>Download.py
Enter album/playlist url: https://www.jiosaavn.com/featured/tip-tip-barsa-paani--hindi/RHhA6i,xnFWO0eMLZZxqsA__
Please paste album/playlist url

**Comment by mpeddu** [comment]
I am also having the same issue try other ones and after all the troubleshooting I left it you can let the dev know.

**Comment by prabaprakash** [comment]
> All packages are installed correctly but now it is not downloading any album or playlist. Its says please paste album/playlist url.
> 
> C:\Users\Desktop\github\saavn>Download.py
> Enter album/playlist url: https://www.jiosaavn.com/featured/tip-tip-barsa-paani--hindi/RHhA6i,xnFWO0eMLZZxqsA__
> Please paste album/playlist url

please check for now, so that I close the issue

**Comment by sankalpgaikwad** [comment]
Thanks, Prabaprakash  Its Working Now.
