### ISSUE TITLE
Download Doesn't Happen

### ISSUE THREAD

**Issue by prospreadsheets** [prabaprakash/Saavn-Downloader#43]
I always getting Please Paste Album/Playlist URL...

Downloaded the latest fixed Download.Py file and all packages are installed.

![image](https://user-images.githubusercontent.com/70800104/92302477-12505000-ef8a-11ea-81bd-be441511aef5.png)

**Comment by prabaprakash** [comment]
update you soon

**Comment by EssentialistStoic** [comment]
I have the same problem.

**Comment by prabaprakash** [comment]
Please check it @EssentialistStoic  @ramatheram . close the issue

**Comment by prabaprakash** [comment]
I put permanent fix. Please check and verify.
