### ISSUE TITLE
Saavn api 

### ISSUE THREAD

**Issue by atulya2109** [prabaprakash/Saavn-Downloader#5]
Hey, I have been looking for saavn's api. I wanted to ask you where did you find the api? Is there any documentation?

**Comment by ghost** [comment]
This is working without it. API is only used for search, playlists and meta.

**Comment by atulya2109** [comment]
So is there any documentation.

**Comment by ghost** [comment]
No.

**Comment by atulya2109** [comment]
Thanks.

**Comment by FatKiwi** [comment]
Another answer: it's easily found on their website and via the mobile app.

**Comment by atulya2109** [comment]
How to find it? Using a proxy?

**Comment by FatKiwi** [comment]
Web Debugger.

**Comment by prabaprakash** [comment]
There are a lot of ways to found out any APP API calls - Fiddler Proxy, Squid etc. I used fiddler.
