### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by shammu4real** [prabaprakash/Saavn-Downloader#6]
Hi while running the program am getting the below error... Pls help.

C:\Users\****\AppData\Local\Programs\Python\Python37\Scripts\Saavn-Downloader>Download.py
Enter the url:https://www.saavn.com/s/featured/tamil/Vijay_Antony_Hits/,FiHYsZ8kVE_
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\Scripts\Saavn-Downloader\Download.py", line 157, in <module>
    soup = BeautifulSoup(res.text, "lxml")
  File "C:\Users\****\AppData\Local\Programs\Python\Python37\lib\site-packages\beautifulsoup4-4.6.0-py3.7.egg\bs4\__init__.py", line 165, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by prabaprakash** [comment]
did you installed all packages `pip3 install -r requirements.txt` ? I checked the link, it's working

**Comment by shammu4real** [comment]
Yes i installed all except: pip install lxml

I get an error...

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\shammu\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Shammu\\AppData\\Local\\Temp\\pip-install-zzrgu6ad\\lxml\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Shammu\AppData\Local\Temp\pip-record-dpjombph\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Shammu\AppData\Local\Temp\pip-install-zzrgu6ad\lxml\
