### ISSUE TITLE
Song title with " aborts the download

### ISSUE THREAD

**Issue by chanpreetsal** [prabaprakash/Saavn-Downloader#8]
A minor issue as very few songs have this tile. If you have a song title with "" in it, for example Mein Agar from "Tubelight", this aborts the script.

**Comment by prabaprakash** [comment]
Could you gave me playlist / album details

**Comment by chanpreetsal** [comment]
Created this test playlist. First song is fine and fails at the second
https://www.saavn.com/s/playlist/chanpreet381/test/d9HR3FV35pNieSJqt9HmOQ__
