### ISSUE TITLE
Anyway to skip downloading existing files

### ISSUE THREAD

**Issue by chanpreetsal** [prabaprakash/Saavn-Downloader#9]
I have a long playlist of over 100 files which I keep updating. Is there a way to skip downloading files the file already exists in the folder? Best to have this as optional as it might not always be desired.

Thanks

**Comment by prabaprakash** [comment]
Sure.

**Comment by chanpreetsal** [comment]
How to enable this? i un-commented the code committed to this but then the script through an error
